name: infinite_canvas
description: InteractiveViewer + CustomMultiChildLayout
version: 0.0.2
repository: https://github.com/rodyavis/infinite_canvas

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

screenshots:
  - description: 'Example of multiple nodes on the canvas'
    path: screenshots/1.png

scripts:
  example:
    - cd example && flutter build web && cd ..
    - dart doc -o example/build/web/docs
    - dhttpd --path example/build/web