name: Publish example and package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'master'

      - name: Install
        run: flutter pub get

      - name: Build Example
        run: cd example && flutter build web --base-href=/infinite_canvas/ && cd ..

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Build Docs
        run: dart doc -o example/build/web/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'master'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub get

      - name: Bump version
        run: |
          dart pub global activate cider
          dart pub get
          cider bump patch

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Bumping version'

      - id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: pubspec.yaml
        
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.read-version.outputs.version-number }}"
          github_token: ${{ secrets.COMMIT_TOKEN }}
  release:
    needs: publish
    # uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'master'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub get
          
      - name: Publish
        run: dart pub publish --force
