name: Publish example and package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'master'

      - name: Install
        run: flutter pub get

      - name: Build Example
        run: cd example && flutter build web --base-href=/infinite_canvas/ && cd ..

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Build Docs
        run: dart doc -o example/build/web/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'master'

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: dev

      - name: Install dependencies
        run: |
          flutter pub get
          dart pub get

      - name: Bump version
        run: |
          dart pub global activate cider
          dart pub get
          cider bump patch

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Bumping version'
        
      - uses: jacopocarlini/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"